DROP TABLE IF EXISTS ELECTRACK.INCOMING_MESSAGES;
DROP TABLE IF EXISTS ELECTRACK.MESSAGE_TYPES;
DROP TABLE IF EXISTS ELECTRACK.SESSIONS;
DROP TABLE IF EXISTS ELECTRACK.DEVICE_LOCATIONS;
DROP TABLE IF EXISTS ELECTRACK.DEVICES;

CREATE TABLE ELECTRACK.SESSIONS (
   SESSION_ID VARCHAR(255) NOT NULL,
   OPEN BOOLEAN NOT NULL DEFAULT TRUE,
   MESSAGE_COUNT INTEGER DEFAULT 0,
   LAST_MESSAGE_TIME TIMESTAMP DEFAULT NULL,
   OPENED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CLOSED_TIME TIMESTAMP DEFAULT NULL,
   FORCE_CLOSED BOOLEAN NOT NULL DEFAULT FALSE,
   PRIMARY KEY (SESSION_ID)
);

CREATE TABLE ELECTRACK.DEVICES (
   DEVICE_ID VARCHAR(255) NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   MOD_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(DEVICE_ID)
);

CREATE TABLE ELECTRACK.MESSAGE_TYPES (
   MESSAGE_TYPE_ID INTEGER NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   MOD_TIME TIMESTAMP NOT NULL,
   PRIMARY KEY (MESSAGE_TYPE_ID)
);

CREATE TABLE ELECTRACK.INCOMING_MESSAGES (
   MESSAGE_ID VARCHAR(255) NOT NULL,
   MESSAGE_TYPE_ID INTEGER NOT NULL,
   MESSAGE_SEQUENCE_NUMBER INTEGER NOT NULL,
   SESSION_ID VARCHAR(255) NOT NULL,
   DEVICE_ID VARCHAR(255) NOT NULL,
   MOD_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (MESSAGE_ID),
   UNIQUE(SESSION_ID, MESSAGE_SEQUENCE_NUMBER),
   FOREIGN KEY (MESSAGE_TYPE_ID) REFERENCES ELECTRACK.MESSAGE_TYPES(MESSAGE_TYPE_ID),
   FOREIGN KEY (SESSION_ID) REFERENCES ELECTRACK.SESSIONS(SESSION_ID),
   FOREIGN KEY (DEVICE_ID) REFERENCES ELECTRACK.DEVICES(DEVICE_ID)
);

CREATE TABLE ELECTRACK.DEVICE_LOCATIONS (
	TPV_ID INTEGER NOT NULL AUTO_INCREMENT,
	DEVICE_ID VARCHAR(255) NOT NULL,
   TS TIMESTAMP NOT NULL,
   LATITUDE DOUBLE NOT NULL,
   LONGITUDE DOUBLE NOT NULL,
   ALTITUDE DOUBLE NOT NULL,
   SPEED DOUBLE NOT NULL,
   HOUSE INTEGER,
   STREET VARCHAR(50),
   NEIGHBOURHOOD VARCHAR(50),
   CITY VARCHAR(50),
   COUNTY VARCHAR(20),
   ZIPCODE INTEGER,
   STATE VARCHAR(20),
   SUBDIVISION_CODE VARCHAR(20),
   COUNTRY VARCHAR(100),
   PRIMARY KEY(TPV_ID),
   FOREIGN KEY (DEVICE_ID) REFERENCES ELECTRACK.DEVICES(DEVICE_ID)
);

INSERT INTO ELECTRACK.MESSAGE_TYPES (MESSAGE_TYPE_ID, NAME, MOD_TIME)
VALUES (0, 'TPV UPDATE', CURRENT_TIMESTAMP());

COMMIT;